frr defaults traditional
hostname {name}
log file /tmp/frr_{name}/frr.log
!
interface lo
 ip address {loopback_ip}/32
 ip ospf area 0
!
interface {name}-eth0
 ip ospf network point-to-point
 ip ospf area 0
!
interface {name}-eth1
 ip ospf area 0
!
interface {name}-eth2
 ip ospf network point-to-point
 ip ospf area 0
!
router ospf
 ospf router-id {loopback_ip}
 network 10.0.0.0/8 area 0
 network 172.16.0.0/12 area 0
 network 192.168.0.0/16 area 0
 redistribute connected
 redistribute static
 redistribute kernel
!
line vty
!
